#include <vector>
#include <map>
#include <set>
#include <algorithm>
#include <functional>
#include <utility>
#include <sstream>
#include <iostream>
#include <cmath>
#include <ctime>
#include <limits>
#include <iterator>
#include <bitset>
#define sz(m)((m).size())
#define all(a)a.begin(),a.end()
#define forn(i,n)for(int i=0,i##e=n;i<i##e;++i)
#define fori(i,m)forn(i,sz(m))
#define each(i,m)for(typeof(m.begin())i=m.begin(),i##e=m.end();i!=i##e;++i)
#define srt(s)sort(all(s))
#define dump(m)copy(all(m),ostream_iterator<typeof(m[0])>(cout,"\n"));cout<<endl
using namespace std;

struct EelAndRabbit {
	int getmax(vector <int> l, vector <int> t) {
		vector<int> m;
		m.push_back(0);
		fori(i, l) {
			m.push_back(t[i]);
			m.push_back(t[i] + l[i]);
		}
		srt(m);
		set<int> curr;
		int mx = 0;
		fori(i, m) fori(j, m) {
			set<int> s;
			fori(k, l)
				if (t[k] <= m[i] && m[i] <= t[k] + l[k] || t[k] <= m[j] && m[j] <= t[k] + l[k])
					s.insert(k);
			mx = max(mx, int(s.size()));
		}
		return mx;
	}
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}";
	cout << "]" << endl;
	EelAndRabbit *obj;
	int answer;
	obj = new EelAndRabbit();
	clock_t startTime = clock();
	answer = obj->getmax(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	vector <int> p1;
	int p2;
	
	{
	// ----- test 0 -----
	int t0[] = {2,4,3,2,2,1,10};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {2,6,3,7,0,2,0};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 6;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {1,1,1};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {2,0,4};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 2;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {1};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {1};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 1;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {8,2,1,10,8,6,3,1,2,5};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {17,27,26,11,1,27,23,12,11,13};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	p2 = 7;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	int t0[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	int t1[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	all_right = KawigiEdit_RunTest(4, p0, p1, false, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Rabbit went to a river to catch eels.
// All eels are currently swimming down the stream at the same speed.
// Rabbit is standing by the river, downstream from all the eels.
// 
// 
// Each point on the river has a coordinate.
// The coordinates increase as we go down the stream.
// Initially, Rabbit is standing at the origin, and all eels have non-positive coordinates.
// 
// 
// You are given two vector <int>s: l and t.
// These describe the current configuration of eels.
// The speed of each eel is 1 (one).
// For each i, the length of eel number i is l[i].
// The head of eel number i will arrive at the coordinate 0 precisely at the time t[i].
// Therefore, at any time T the eel number i has its head at the coordinate T-t[i], and its tail at the coordinate T-t[i]-l[i].
// 
// 
// Rabbit may only catch an eel when some part of the eel (between head and tail, inclusive) is at the same coordinate as the rabbit.
// Rabbit can catch eels at most twice.
// Each time he decides to catch eels, he may catch as many of the currently available eels as he wants.
// (That is, he can only catch eels that are in front of him at that instant, and he is allowed and able to catch multiple eels at once.)
// 
// 
// Return the maximal total number of eels Rabbit can catch.
// 
// DEFINITION
// Class:EelAndRabbit
// Method:getmax
// Parameters:vector <int>, vector <int>
// Returns:int
// Method signature:int getmax(vector <int> l, vector <int> t)
// 
// 
// CONSTRAINTS
// -l will contain between 1 and 50 elements, inclusive.
// -Each element of l will be between 1 and 1,000,000,000, inclusive.
// -l and t will contain the same number of elements.
// -Each element of t will be between 0 and 1,000,000,000, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// {2, 4, 3, 2, 2, 1, 10}
// {2, 6, 3, 7, 0, 2, 0}
// 
// Returns: 6
// 
// Rabbit can catch 6 eels in the following way:
// 
// At time 2, catch Eel 0, Eel 4, Eel 5, and Eel 6.
// At time 8, catch Eel 1 and Eel 3.
// 
// 
// 
// 1)
// {1, 1, 1}
// {2, 0, 4}
// 
// Returns: 2
// 
// No two eels are in front of Rabbit at the same time, so Rabbit can catch at most two eels.
// 
// 2)
// {1}
// {1}
// 
// Returns: 1
// 
// 
// 
// 3)
// {8, 2, 1, 10, 8, 6, 3, 1, 2, 5}
// {17, 27, 26, 11, 1, 27, 23, 12, 11, 13}
// 
// Returns: 7
// 
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
