#include <vector>
#include <map>
#include <set>
#include <algorithm>
#include <functional>
#include <utility>
#include <sstream>
#include <iostream>
#include <cmath>
#include <ctime>
#include <limits>
#include <iterator>
#include <bitset>
#define sz(m)((m).size())
#define all(a)a.begin(),a.end()
#define forn(i,n)for(int i=0,i##e=n;i<i##e;++i)
#define fori(i,m)forn(i,sz(m))
#define each(i,m)for(typeof(m.begin())i=m.begin(),i##e=m.end();i!=i##e;++i)
#define srt(s)sort(all(s))
#define dump(m)copy(all(m),ostream_iterator<typeof(m[0])>(cout,"\n"));cout<<endl
using namespace std;

struct ScheduleStrength {
	vector <string> calculate(vector <string> teams, vector <string> results) {
		const int q = teams.size();
		vector< pair<double, string> > v;
		forn(i, q) {
			int n = 0, d = 0;
			forn(j, q) if (i != j) {
				if (results[i][j] == '-') continue;
				forn(k, q) if (j != k && i != k) {
					n += results[j][k] == 'W';
					d += results[j][k] == 'L';
				}	
			}
			v.push_back(make_pair(double(-n) / (n + d), teams[i]));
		}
		srt(v);
		vector<string> r;
		fori(i, v) r.push_back(v[i].second);
		return r;
	}
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <string> p1, bool hasAnswer, vector <string> p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p1[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	ScheduleStrength *obj;
	vector <string> answer;
	obj = new ScheduleStrength();
	clock_t startTime = clock();
	answer = obj->calculate(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(p2.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << "\"" << p2[i] << "\"";
		}
		cout << "}" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "{";
	for (int i = 0; int(answer.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << answer[i] << "\"";
	}
	cout << "}" << endl;
	if (hasAnswer) {
		if (answer.size() != p2.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p2[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	vector <string> p1;
	vector <string> p2;
	
	{
	// ----- test 0 -----
	string t0[] = {"BEARS","GIANTS","COWBOYS","BRONCOS","DOLPHINS","LIONS"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"-WLWW-","L-WL-W","WL---W","LW--L-","L--W--","-LL---"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	string t2[] = {"BEARS","DOLPHINS","BRONCOS","COWBOYS","GIANTS","LIONS"};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"BEARS","COWBOYS","GIANTS","PACKERS"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"-LLW","W-WW","WL--","LL--"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	string t2[] = {"GIANTS","BEARS","COWBOYS","PACKERS"};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"AZTECS","COUGARS","COWBOYS","FALCONS","HORNEDFROGS","LOBOS","RAMS","REBELS","UTES"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"---L-L--W","--LL-LWL-","-W--WWLLW","WW---L--W","--L--W-L-","WWLWL-LW-","-LW--W-L-","-WW-WLW--","L-LL-----"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	string t2[] = {"HORNEDFROGS","COUGARS","RAMS","LOBOS","REBELS","UTES","COWBOYS","AZTECS","FALCONS"};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"E","D","C","B","Z"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	string t1[] = {"--LLL","---LL","W---L","WW---","WWW--"};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	string t2[] = {"D","E","C","Z","B"};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// A common way to rank athletic teams is based on each team's winning percentage. However, when two teams have similar percentages, the team that played against better opponents will be ranked above the team that had easier opponents. The measure of how difficult a team's opponents are, is known as the team's strength of schedule. A team that has faced tough opponents is said to have a strong schedule, and a team with poor opponents is said to have a weak schedule.
// 
// 
// We will use the cumulative winning percentage of Team X's opponents (the teams that Team X played against) as a measure of Team X's strength of schedule. This percentage is the number of wins recorded by Team X's opponents divided by the total games they played, excluding games that were played against Team X.
// 
// 
// 
// Given a vector <string> of teams that contains the name of each team and a vector <string> results that indicates the outcome of games played during the season, return a vector <string> containing the names of the teams, ordered from strongest schedule to weakest. Teams with equivalent schedule strengths should appear in increasing alphabetical order.
// 
// 
// 
// Element i of results corresponds to team i whose name is found in teams at index i. Character j of element i of results will be one of 'W', 'L' or '-' respectively indicating whether team i won, lost, or did not play a game against team j.
// 
// 
// DEFINITION
// Class:ScheduleStrength
// Method:calculate
// Parameters:vector <string>, vector <string>
// Returns:vector <string>
// Method signature:vector <string> calculate(vector <string> teams, vector <string> results)
// 
// 
// CONSTRAINTS
// -teams will contain between 3 and 50 elements, inclusive.
// -teams and results will contain the same number of elements.
// -Each element of teams will contain between 1 and 50 characters, inclusive.
// -Each element of teams will only contain uppercase letters ('A'-'Z').
// -Each element of teams will be distinct.
// -Each element of results will contain N characters, where N is the number of elements in teams.
// -Each element of results will only contain 'W', 'L' and '-'.
// -The ith character of the ith element of results will be '-'.
// -If the jth character of the ith element of results is 'W' then the ith character of the jth element of results will be 'L', and vice versa.
// -Every team will play at least two games.
// 
// 
// EXAMPLES
// 
// 0)
// {"BEARS",
//  "GIANTS",
//  "COWBOYS",
//  "BRONCOS",
//  "DOLPHINS",
//  "LIONS"}
// {"-WLWW-",
//  "L-WL-W",
//  "WL---W",
//  "LW--L-",
//  "L--W--",
//  "-LL---"}
// 
// Returns: {"BEARS", "DOLPHINS", "BRONCOS", "COWBOYS", "GIANTS", "LIONS" }
// 
// This season's results gives us the following win/loss records:
// 
// 
//         wins - losses
// BEARS      3 - 1
// GIANTS     2 - 2  (1 loss to the BEARS)
// COWBOYS    2 - 1  (1 win against the BEARS)
// BRONCOS    1 - 2  (1 loss to the BEARS)
// DOLPHINS   1 - 1  (1 loss to the BEARS)
// LIONS      0 - 2  (did not play the BEARS)
// 
// 
// 
// The BEARS's opponents are the GIANTS, COWBOYS, BRONCOS and DOLPHINS. Their combined win/loss record is 6-6 (6 wins, 6 losses), but when we exclude games played against the BEARS, this record becomes 5-3. So, the BEARS have a schedule strength of 5/8 = .625
// 
// 
// Here are the cumulative records and winning percentages calculated for each team:
// 
//            Record    Winning %
// BEARS      5 - 3    5/8 = .625
// GIANTS     4 - 4    4/8 = .5
// COWBOYS    4 - 3    4/7 = .5714
// BRONCOS    4 - 3    4/7 = .5714
// DOLPHINS   3 - 2    3/5 = .6
// LIONS      2 - 3    2/5 = .4
// 
// 
// 
// 1)
// {"BEARS",
//  "COWBOYS",
//  "GIANTS",
//  "PACKERS"}
// 
// {"-LLW",
//  "W-WW",
//  "WL--",
//  "LL--"}
// 
// Returns: {"GIANTS", "BEARS", "COWBOYS", "PACKERS" }
// 
// 2)
// {"AZTECS",
//  "COUGARS",
//  "COWBOYS",
//  "FALCONS",
//  "HORNEDFROGS",
//  "LOBOS",
//  "RAMS",
//  "REBELS",
//  "UTES"}
// 
// {"---L-L--W",
//  "--LL-LWL-",
//  "-W--WWLLW",
//  "WW---L--W",
//  "--L--W-L-",
//  "WWLWL-LW-",
//  "-LW--W-L-",
//  "-WW-WLW--",
//  "L-LL-----"}
// 
// 
// Returns: {"HORNEDFROGS", "COUGARS", "RAMS", "LOBOS", "REBELS", "UTES", "COWBOYS", "AZTECS", "FALCONS" }
// 
// 3)
// {"E", "D", "C", "B", "Z"}
// {
// "--LLL",
// "---LL",
// "W---L",
// "WW---",
// "WWW--"
// }
// 
// Returns: {"D", "E", "C", "Z", "B" }
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
